import plac
import os
# from visualise.bulk_index import bulk_index
from visualise.helpers import gen_data_frame
from visualise.plot import generate_plot

curr_dir = os.path.dirname(os.path.realpath(__file__))

def main(path:("str: Path to the cache.sqlite file generated by nyx", 'option', 'p')=curr_dir, points:("int: Number of points to plot on the map", 'option', 'pts')=20):
    try:
        f = open('cache.sqlite', 'r') # Just to generate an exception if file is not present
        f.close()
        dataframe = gen_data_frame(os.path.join(curr_dir, 'cache.sqlite'), points)
    except Exception as e:
        print("Please provide a cache.sqlite file or its path", e)
        return None
    generate_plot(dataframe)
    # ...

if __name__ == '__main__':
    import plac; plac.call(main)
